serviceCredentials:
  BANK_SERVICES_FRONT_UI_SERVICE_CLIENT_SECRET: "__FRONT_UI_SERVICE_CLIENT_SECRET__"
  BANK_SERVICES_ACCOUNT_SERVICE_CLIENT_SECRET: "__ACCOUNT_SERVICE_CLIENT_SECRET__"
  BANK_SERVICES_CASH_SERVICE_CLIENT_SECRET: "__CASH_SERVICE_CLIENT_SECRET__"
  BANK_SERVICES_TRANSFER_SERVICE_CLIENT_SECRET: "__TRANSFER_SERVICE_CLIENT_SECRET__"
  BANK_SERVICES_NOTIFICATION_SERVICE_CLIENT_SECRET: "__NOTIFICATION_SERVICE_CLIENT_SECRET__"
  BANK_SERVICES_EXCHANGE_GENERATOR_SERVICE_CLIENT_SECRET: "__EXCHANGE_GENERATOR_SERVICE_CLIENT_SECRET__"

postgresqlCredentials:
  password: "__POSTGRESQL_PASSWORD__"

keycloakCredentials:
  adminUsername: "admin"
  adminPassword: "__KEYCLOAK_ADMIN_PASSWORD__"

grafanaCredentials:
  adminUsername: "admin"
  adminPassword: "__GRAFANA_ADMIN_PASSWORD__"