serviceCredentials:
  BANK_SERVICES_FRONT_UI_SERVICE_CLIENT_SECRET:
  BANK_SERVICES_ACCOUNT_SERVICE_CLIENT_SECRET:
  BANK_SERVICES_CASH_SERVICE_CLIENT_SECRET:
  BANK_SERVICES_TRANSFER_SERVICE_CLIENT_SECRET:
  BANK_SERVICES_NOTIFICATION_SERVICE_CLIENT_SECRET:
  BANK_SERVICES_EXCHANGE_GENERATOR_SERVICE_CLIENT_SECRET:

postgresqlCredentials:
  password:

keycloakCredentials:
  adminUsername:
  adminPassword: