serviceCredentials:
    BANK_SERVICES_FRONT_UI_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:bJKFJkDoheyyQ5sbNCOAhvKbakWr7BM61dHfeYMKH7HA/Q==,iv:Jjs48ZxSu9GOFmdsprDd9MC0sNC4dZnqpdM7+Ss6YSk=,tag:cbsBMv3A+YC6DQk9mDGcCA==,type:str]
    BANK_SERVICES_ACCOUNT_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:TiUxV2YnbA7lA1F/ae/z0UdqrPq6XG9ywI54p+7gHB/j,iv:wLNtgPVYDKklM0vm30KfZyatVIoLxLo+m98bqlGsO40=,tag:IS/7JqfmmHFH01c3DZ67mg==,type:str]
    BANK_SERVICES_CASH_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:CzwxidlY2f8hsEqvajMQXgcY6xJ6lvAD5Zkul7S1,iv:fRk1ZY4UFNhzk/qosHyMriLzyHRZdBj7lL8wpL+9k0c=,tag:4DHzO2CIVjcqHsGLbJLEMQ==,type:str]
    BANK_SERVICES_TRANSFER_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:Ud6Z+PmgfTSlLSDfF1U53KFd4EfCcRy5x5HvSA5nVxtAsA==,iv:RGm3pknmThv/R6yg/+Fxn4Oe6RJMpB2afALKgM/mgRw=,tag:r5KhBTg0YbY9uN+AhJafjQ==,type:str]
    BANK_SERVICES_NOTIFICATION_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:1qiyqeWx2VbCiW5g1r48kuv5rg6A101YK8qL3sTFzO/GY485mQw=,iv:ptScW4FtfCxVu7NHUIxaHNk7yB5oZz6czcJtyQ0zCxU=,tag:UVQs22R3uSmXvngG9YSnKA==,type:str]
    BANK_SERVICES_EXCHANGE_GENERATOR_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:FZLgdlmINHEmaR3vTjXLl4bNQjmMiDCV2gtGK/tilkfr2+4juke4FfNuc9I=,iv:aRypo8r9u9b9z8EN5tOgCHwROdWxAfd+abcPzr5ezL4=,tag:R4qZYWi0nsIacs5V72ovwA==,type:str]
postgresqlCredentials:
    password: ENC[AES256_GCM,data:B49uAD1TF9k3LUGdaRwYlxsIUCrqpJo=,iv:uGKp2vsF8yX3bORB/N8osx0BA0fi3BZYEtbGzUq0Akk=,tag:9w4oz5PPmt0duHsQbQXyPg==,type:str]
keycloakCredentials:
    adminUsername: ENC[AES256_GCM,data:xFmSNcm9Ifd4y3SWYAKU4HukYm6cjVQJuaU2,iv:hY75+bNAl6pfOTz8zkznsK54lWzBQbgecYHJBy5ghmM=,tag:wifpKVK7iIQv5eAhtlZezQ==,type:str]
    adminPassword: ENC[AES256_GCM,data:4/U5wI93BLxRs9vNcpulzLFyD/h5XR23ftY3,iv:lQWkLqx5BIO24jofHTFSDefkeoWTlZ3xEvbtF6IAfpc=,tag:MKnUdyT24kvpecJJ4HNeJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yxaztnh2jc4740e33fcxa8gy996a959f2548xucplkss4k483p6ss8jryg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZzI1UjBuaU9ZQ3hkazA4
            TmRVTk0xaElvS1B5d2YrOUhJT3Z5UWR1eHkwCnZNU3A3NFgxUFRPWWFTdmd2dDAw
            dE5pWmoyenlhUFB2NW5BdzhWZ1A4YjQKLS0tIGh5aHV2VU1Yb0ZZKzdsOUpmeWlm
            ZndBTTdxcnRuaTU4MDNPaVRvdzFQcVUK1RWRrYrhC+0VX0oGNu85x2daLWI2qbH2
            7//ekvr0d24SZ/q1KFXvcIrFtIXf0YLyVv0DG2JG5FauRIhMsoyE0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-23T18:59:14Z"
    mac: ENC[AES256_GCM,data:4Qs9hkL04C/jb6lrHhrimNGtC2mRsPby5WtdlJ4qYhszbds1bIjqx8Ii2+ALDwPlxDkfxFmdNGO/nEc93I635KmHYPvfEq/jakwbdZ0S9SrbRkfXRGnP5aYxtJ6N/nqI+V4YUlH4+NUXNVQOov7MeZmL4sc4fX0kqGJM920Nkx0=,iv:LvT3cWu8q6NB0/UT4IcmbFT4ofpYiDMiwWf6L/qdZ3U=,tag:cnUOd3P2cTSbqxiHD00okQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
