serviceCredentials:
    BANK_SERVICES_FRONT_UI_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:ijeonb+jkOivZS1I9Y687jcss1kEviw/S+jJmqdE6+n7Yg==,iv:Jgl/CyFITR3S4dPRh6bVVoHCOK6HVOaKL/uEfJfgNyY=,tag:cckLE4aY9PiOLa4ZAczTAQ==,type:str]
    BANK_SERVICES_ACCOUNT_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:TDd5mbHDJM1E4AW5Vk226DyntooNPzGh7yA38M2feyz3,iv:VZMIfxIsmwpkGj0frH50sM187Xcrdrr4ZefHrvOVw+o=,tag:dXGLUeIwWrbDyiVZgyLl4A==,type:str]
    BANK_SERVICES_CASH_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:TBNZcMbJL54/y4Ac39DrVevM0gVrkE12R8P/vjvp,iv:fNi9kBaIGvJWgA34PboOV/ZIETR+EKCz2dlDj4Nq2qY=,tag:FrdgN6wdvGjlkw0o9Wv7XQ==,type:str]
    BANK_SERVICES_TRANSFER_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:i6EhZpA1G6rQjeACvJGTMe+lxHwtA6OTNo9FDumhWVpfHQ==,iv:jcrpNlL6gSIY7epUAMBGLYdpEaZrrnK7C8IL/Gfm+Ds=,tag:o1X/LR8POkhmPMQusC/aSw==,type:str]
    BANK_SERVICES_NOTIFICATION_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:dSMFxcUc9tBMLCGerqwhUBbLba+fETSlHdoranq5vg1KlC+1/6w=,iv:5f3r88u+GUbA5tTBiCXpefcomQz7Tfo0cLFzLe8d3As=,tag:KlmuOcgrzBSxbVN6b8k3rQ==,type:str]
    BANK_SERVICES_EXCHANGE_GENERATOR_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:lKS0YfZiJtmPRC+Zu48L/feG2Bh7/15/dMUeavRTLLXMJeiUnhV9bTaOjoI=,iv:FTsAmJYfPnQTymuYgRXijTC411HN5obdMxJCGv04em8=,tag:2YnsfmErE+5pMcy20MjGvg==,type:str]
postgresqlCredentials:
    password: ENC[AES256_GCM,data:XG/H5G1ZzRgArq55SPVdwQvcu3iCZtk=,iv:jvpHwiWHdZWi7A5/6KD4fIX4gNwLVc0KLVklIzGcOgw=,tag:jZzVavqmwI/o34JvU5uW7g==,type:str]
keycloakCredentials:
    adminUsername: ENC[AES256_GCM,data:bbVmY+Q=,iv:3Q8vVlY0cR6RkDzMu+jIUuTIvp+KsL063kQFl8kq9Es=,tag:V45Wr9DgzVf1cWztYOLBzw==,type:str]
    adminPassword: ENC[AES256_GCM,data:flMZLkZX8hp1kMvxMYc2/d6qX15bL1yA17W7,iv:hqR3xJ6lNq6/l/TLfzY0Zre535W2LgXwHlx6hajxk+g=,tag:Zh+w8rFFUd8OxCMhkfbnXQ==,type:str]
grafanaCredentials:
    adminUsername: ENC[AES256_GCM,data:5uOmK7o=,iv:b+av9I19QCoCUhm9TZxwJ5gFPrxgcaEAqEcT32KQHpE=,tag:0oid0fbYRHwiOmcCd+ueMQ==,type:str]
    adminPassword: ENC[AES256_GCM,data:Xtb0jxMoi2gQRQjGhAuSGtvhYp/Wr6Q4ri0=,iv:cfSh9kI9/wapQ2StFYmb8h2LYZc1MJMspe0S7xXM0LY=,tag:h1BdDC1Xe7QW+qOj9Jxt2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yxaztnh2jc4740e33fcxa8gy996a959f2548xucplkss4k483p6ss8jryg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweDMxZ2laZzloYmEwMWxM
            RUFPTlExQjlucE5oZG9qTHFRZ3paTVlEOVVJCm0wWjlrcytTUGkxZmhuc0FwdFBY
            b0k5YjVXRnUvd1hiTkszT0JKSHIvK2MKLS0tIFFPeDJFc3ZkRkZKODBHS3lhZ1J2
            UVI5L1orNXM4b05zTVdnWFM3N2VyWDQKOMa9Z4AloxURKY14w2KUhJYHKZtNzCCH
            Ow42P25C/j1GHzYB/gVrp6uGHrDsQU6Y0W4+vOIFFPaVN0SWNTRGxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T20:12:29Z"
    mac: ENC[AES256_GCM,data:cui4BJQ/Z3my6X5WtzgxP7RTUxi0Ea6omJ9ukuqHDUXDIYK1B2h2EHl+bKH0sH2FhZ0+Ae09CfynMx6m8Hg2S9IcmSnNv5pwnY4HiUSKJsqGsR9zm1ggkC1i1ogVejGqTVBfOO5ARU86BkREm30pcdGHA03p+ZJdpx8FEUNTiTc=,iv:TiSe+xqtjIbkUX1odbKNWLnKrYPwWW0rgxQEiPC5wuE=,tag:qmBTaKOgRnRseT4Jlcsk0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
