serviceCredentials:
    BANK_SERVICES_FRONT_UI_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:gd3HM7sKGapeaxNkX9L67pv0gey1hgvXUlG5KGG+2CvH4w==,iv:8IcRZG7jsqSlO0eAsxRLjoMnQCa0be24JgLxU3tSkiI=,tag:FNcQ8tzb1FPH5jbUZ+GFhw==,type:str]
    BANK_SERVICES_ACCOUNT_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:tqPQbuaKIARJ5qCmUJRjHLSGMmp8olfC3ekhRPKHImzD,iv:WDu2QHsHAJJk1B+Qnm0cC5uQYf+JkyuqLmjpUf6Jy+4=,tag:FzqmX8wlsJqS19rQK8my4g==,type:str]
    BANK_SERVICES_CASH_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:fx3LP4bype7h2NfaKCKtMKMGPZImjYcyBxjuSdjT,iv:IINRxSic1jXW0WitW/s0Xa28HBeUzGEGb8NXKt572Pg=,tag:pkLbVXqXHlEcd6+SfN0iWA==,type:str]
    BANK_SERVICES_TRANSFER_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:MTs0L4buZ/9ZprFGGqQ5uozoT6s0pdxZ0d3DTidNWPsvcQ==,iv:AGa3+okEjPVOFZJtArg0ddINQefZU2711L4KEwWWFfA=,tag:pbvJRt1/CVhVX0vxt709fw==,type:str]
    BANK_SERVICES_NOTIFICATION_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:hq1JNfzVmylbpwDJriesaJ8yWJM5u4X99G66mjvQFscFnmJm/lg=,iv:CJD+OoXE4WgNgAUjaOb+6tP2n5ux+vSKCwHaDDxOaYM=,tag:cipzYPbLi4FoRFTbNtYnVA==,type:str]
    BANK_SERVICES_EXCHANGE_GENERATOR_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:a+AlwTjwiN4WWXt2fOpON7QxdhwGx4G4AzYGqZG7pzJjWjzO4y1jq3x99Do=,iv:5Ep6W4modiinXX6YiUipON7UecwBiVjhsrBxhTfqdhE=,tag:Hi4DSz9SxUMQwFKQizZNjQ==,type:str]
postgresqlCredentials:
    password: ENC[AES256_GCM,data:lTsSI+JIRToI7WgrMaLvzlzf/0X3Vw8=,iv:xUUIyfLQbjdOp+RAGl4dcPHMlaSfOYaWl+/Q4G5k75c=,tag:w1tpn8iwtZGe/Z5jLcK5Ug==,type:str]
keycloakCredentials:
    adminUsername: ENC[AES256_GCM,data:EErnvsY=,iv:jFC2G3Im0UFU64vMwofcANivb/ERTIgXisOnKQBbaUg=,tag:3PcxUXiX0Fqvvh1mBgfrog==,type:str]
    adminPassword: ENC[AES256_GCM,data:zWt/p1FWrYX36IXmUF0TwPzrwxiD01R9/YsI,iv:7K+AARoVbeNC16wXt+MlqNX3Na7rLtAYVw1254Z1l0o=,tag:mzbgDKGe3VcGakez9ko2Yg==,type:str]
grafanaCredentials:
    adminUsername: ENC[AES256_GCM,data:/F7buUc=,iv:Pxt1I7QfMe3CJBg3lRMQ+zF0MwmEaKaNwzQOk7P98C4=,tag:0smWBCac7QVdi4XW/JDRTQ==,type:str]
    adminPassword: ENC[AES256_GCM,data:gXgwBpym7eha/B9E3cWb7K9lAIeCAJ2h7Ws=,iv:9wSAqSYFCYtfaTvjDIDRvO2GVQXrA8bwAMEDHSRwFP8=,tag:Ijrc5Nj69+zOq0S91Hx62w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yxaztnh2jc4740e33fcxa8gy996a959f2548xucplkss4k483p6ss8jryg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFY0FPaGFYNjliU0dySnZu
            bFhacEc3U0QvUGs0Zm8xRDJ5S2VTclBUb0dvCkxRZW9lSnNoOE5TU0E4UTZ1TW15
            UVBucXZRa2Jld3lweFU1NGRVRmI2RGcKLS0tIEk5ek1HZU05NkhqVkN4YXlMWmtj
            YTVFeitvU3FCWElMNjg3cE5YaWF0OUUKIdme9UaRY4yHdLqxyUldRJuhHw4zbP+8
            uWs02w1QicO3XhY/ogdpiGfQRhqleHNavTilT+eGPUCGds1EI5dDKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T20:11:54Z"
    mac: ENC[AES256_GCM,data:TNNsGhdIMQsXMwX3rC55oKdSuSdmGIdXGKDzWOV9/GC8oGAtTCS5bR2BCkcbQMTG3YDOIXI/UHwj0ZCbq46teuwrPAOZJ9mXw0pFv2LSbyrei/e2gB1zB+M9visupQk83Huzl7u5WUj5biSbMv3LbG03hBs5jv82Pfo0P7T9n4Y=,iv:9E7ZvVxX+yq5HLtCsCF9+Rpz1MKJLtOOwP1zpFKs+iw=,tag:zapKfaOERgcCpAD5ir85+A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
