serviceCredentials:
    BANK_SERVICES_FRONT_UI_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:plBjtFDMxu8BTM4Xnzt5t3eDcrwtRd3OU1laBDP00iWkTw==,iv:7/fmMyp/7xqCub6/qKv0xPucKueEadAims7IMLeKZz8=,tag:7HDxJOkvsfe56nMY02LWDg==,type:str]
    BANK_SERVICES_ACCOUNT_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:KP0HUHGSTsJUgDCbpR6ktkszZptit70bjU8stE8f37RP,iv:cDea5D3pbMuYZO78nElxIveLxnqUSfui+DGsy5BEqrQ=,tag:51Mai18sW1SpEHIX/QLmkg==,type:str]
    BANK_SERVICES_CASH_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:gLODW8ostHghthf12FYxSPKWM3WJqkjb0ofkZRCq,iv:MOfdI4Ij+/qot+U/OX6QCjP3N/aAClfuKhTmbeopLXY=,tag:Wvz55pMq5QUAMUgnYIu/LQ==,type:str]
    BANK_SERVICES_TRANSFER_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:7dQmOJr9S08c2szxJt519rdi/sQRiNIZDuDhxBgwXTSbXA==,iv:07i0XQo842244UZQrXT3JIeT8GSh5apa9afD8G2B9JY=,tag:t6Fw3iClpiynqVsE0GuxVg==,type:str]
    BANK_SERVICES_NOTIFICATION_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:nNGt3GPifZhVgSDZirkIZ01+vzBhLO7lJ6IrY0NRLJFUBavNAbU=,iv:dNqssGOaA8DhLYc1FV52EHouVlCo8w4IVAFf8q/UcJ0=,tag:xbglIqVAzxzZ2wjpeAT0Lw==,type:str]
    BANK_SERVICES_EXCHANGE_GENERATOR_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:HA/6ZMwyjYva8kn58dxlDUwnTp1Hb93s5DtijwUMppQBplVH0QGm0625igU=,iv:3zda21SerGhMfspFO4cB55HvcgwVYnD3fqHOn27+eZ0=,tag:JH+gv2RS8WhvA02gt+GimA==,type:str]
postgresqlCredentials:
    password: ENC[AES256_GCM,data:7SvknCmf3J2t0BKW+l5ISRCdqbnu76Q=,iv:SWKHjfULCKJjYkoizdwDL8P5gFgl/ajt0KK18MZXK+8=,tag:2UcnFivlKsSSEygzkhdjug==,type:str]
keycloakCredentials:
    adminUsername: ENC[AES256_GCM,data:71LXs/lg28iHNtERApVNnR8kS2GC10G8WarK,iv:cO/qXELA66axclRxvr1cW/kzjqI4OdSFu16xDBzXr44=,tag:UAsEbSAY1Pa9uiNgCdyOMg==,type:str]
    adminPassword: ENC[AES256_GCM,data:0zlVFV1AcU1Qxcm69ep096nbgxCC78GNcNkI,iv:CM1KG+n7wPG4HMQJ20fr8hep6fvHcnrGq5jJIFNLO7A=,tag:YZ6tMI5i/6A5LiGZizuGLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yxaztnh2jc4740e33fcxa8gy996a959f2548xucplkss4k483p6ss8jryg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwd2l1OEsxbGRNYTkwa1Jp
            SDVtWDNHY2VXS1I5QmNSU0k5anBPTGNuS2tBCk1SSUNoSW05bmc4cW1nVXpxcTgv
            dlkxYWxzbGJJS1JqbDVTQnlUK1RvbGcKLS0tIEpDemt6dlp6cm4rd1lUdy9NUUxz
            MHlTd0tSSFlYbXZZSklhNmNHelFXd1kKY/gbvZFB+52z2xKPIOTDh1RkkIl/T4ll
            m9MsKJqTvdPuOOXONJUANVXXqLtAgakB67uq8Q62ojR+ZvyUCYvZ7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-23T18:59:11Z"
    mac: ENC[AES256_GCM,data:XWZlMKjrY/D43WS8cWtATOCFv9OZscFeEHiSk3UijEWP6eSbDlQzuwHr9NFVQf5ibF4Qdf6oksBccAiynLdrYJSRi/A6vKdmhr0SHwtZqPCEV3j5i3zhYx2QNRx+/jQqpiuFw8zryk31zqtFjJJ5WQ6u8rKZrmEqgP8dGyXyyRw=,iv:Sc9injT1PV9z6RT409gYVnF12Ib17sLfNmAd1xpeE6E=,tag:Z9Z8GwPCnd4EpKLCx2lx1g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
