serviceCredentials:
    BANK_SERVICES_FRONT_UI_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:OdhxFivuj4BTANzSCq0kdmIN+tvoHbTEquUeXLtAac5f6Q==,iv:uM12C8DZRbHNFWhyqfHRA8yXOI7y1ro3rzvIPFDTDXs=,tag:7QPcrjZsjNTTtpmMlgRRBA==,type:str]
    BANK_SERVICES_ACCOUNT_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:86w9H0PKIbGUgTKVjthhRMPw8xfz+jwF1R/XmIUhCuGo,iv:9QfuX0R1BFDe5RUH8rzgWKgE9ACTbP41AksX8wviueY=,tag:L62xxM7OVJkT3lC7DkSfjg==,type:str]
    BANK_SERVICES_CASH_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:efZup/7SmA1sDMDdFnqogR34CbwQqjfDbHeq9kMI,iv:JudiS8Cww8Qw0kpYmsca1DXVlxH7B8AZVCzepE3GV50=,tag:NLE+9S4gag4CB7Ja4Z3O5A==,type:str]
    BANK_SERVICES_TRANSFER_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:x9/OQtUh7pecnlBccDqCE+5Ch1LH2Xrr4P5sJw8GtxPDZg==,iv:DsAdV5+IrBE4TfGa2Nj5O0ergv6mZrYqEO1ZVftUA8E=,tag:+49d3ZEQLVXwrfRUd48I7w==,type:str]
    BANK_SERVICES_NOTIFICATION_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:D5ur27mqX+NJzY8/EHp35ONEkfGsmKbgD+Gm6QcOHlb3L68HffY=,iv:pZ7zx293t3nP8ujpIYvcjzMapxDkDQWOUvUcR19vW7E=,tag:qn6Ytce3sWdK6y6gfVpobA==,type:str]
    BANK_SERVICES_EXCHANGE_GENERATOR_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:sdG+T+bG99sKuuKIje6DKyz/auy6ppmQNiLRCgJMiwgYwvlhuw7G/8mZ8Ro=,iv:2LoIPmAvfNTzKvUbH71Qr1CylKIrVDbOJhpQ4KCgW1o=,tag:IzmpWdnqrp9ZCxr9eHIDDQ==,type:str]
postgresqlCredentials:
    password: ENC[AES256_GCM,data:JgHKArMGFw2yMHomFXWFHS8udbyCE0I=,iv:L+ThhZqZfOKA9xNqYs1vTtnX/DbHH8ftu4Y0PyJUj6A=,tag:xk5gJ0p9Gq16l2H0USkydw==,type:str]
keycloakCredentials:
    adminUsername: ENC[AES256_GCM,data:WY1mUOA=,iv:080E7050+WtLZyHT46kbtMTeQZkPcSFTsn8s7bkp6vY=,tag:5vDstd0qWuokk2q+aePABQ==,type:str]
    adminPassword: ENC[AES256_GCM,data:cfrjeNyecmeBvx5pBDQwtMnYpEI2yy+j96Bn,iv:VzwZlJsMhkTNUH7/2L//6lDi+lqbCio+DYgVMUu2E6U=,tag:ssxYW3FF0xpe/qBRisT6nw==,type:str]
grafanaCredentials:
    adminUsername: ENC[AES256_GCM,data:t9u5Mmw=,iv:tFLmVezIHjXTEVJPcS4DKKickYLEO4F5GWkCkjmQVKA=,tag:jtzMtuqtiUA+28DhhCLQsA==,type:str]
    adminPassword: ENC[AES256_GCM,data:fcpomH/Yr4jIDMbIbKMaTS7Q/DC28nMZOzw=,iv:dQeM4CAEoa4af54uJvhOzYwSTVbIL7+sUh+uLbjbI2o=,tag:SCgIWtRqt1RMXfYT3CD4TQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yxaztnh2jc4740e33fcxa8gy996a959f2548xucplkss4k483p6ss8jryg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQm1OK2w5a0J3NnNHSXBN
            cnU0YnloQUE2LzZkKzhxS2pwOERXcy9jTzNnCkRVajBOVjRvYjREd3Rrc1RMeTBj
            aUxkWEVCSmVYaVUwelhtQ0JsYjBmTmsKLS0tIFpES1ZZTzR5bkFJL3dIcnBCdUc4
            bEpFYzZMNjFQZkVieEFsMVFGMzZndmsKNM0xQDuMFWxYyyQ1l3569CL2X/vFf86d
            DOnECP56p1LiKAZXWR87rbsindpqu2AlUwardcDlxg/Ube16Mfn4rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T20:12:11Z"
    mac: ENC[AES256_GCM,data:YKjeCmaMlbwMnl3yB2ImN+KU27se9XIRYKnA3LWYoT3tLnuedxEozTKTF9LBjfiDpAuTEJf/Ty0dIsCoS99qsehIOaN+BybxkSphbMcy6EueHS9fvlzZV6gOhims5As74eUKnzMwbIUNdQ8SaXis5fTwa4s9jVaK+fA4AOTRbfc=,iv:jfDxBX/sARtY1JL9cQcPocV+sZ2MIHJ7IhYr5E60QXg=,tag:2Jbr/YOqBG5LP2MrqruNIg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
