serviceCredentials:
    BANK_SERVICES_FRONT_UI_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:H593VUX3iDDG0hjFZPS7OnTBNtDEBU5VKgMRLtlfIpfbrQ==,iv:01aYLVb5b/38CaT/w4Sahbz3uNESYbrOX3JcM8AIN4I=,tag:XJYbiO8601EXPR67DorzWg==,type:str]
    BANK_SERVICES_ACCOUNT_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:Q/3GTGjREr+6dlmphFmlIp2Q/8yxTV4omxGin5W+cUAS,iv:p6DoEcU6tZpGOQOT/40WpNkTKBENflky5NyU5EgBWIg=,tag:RIdx/lFnwxRquPZtYFkDew==,type:str]
    BANK_SERVICES_CASH_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:eMQPDhem5LVcF6e6dx0K8DgWjizPmEprYBoS5u4v,iv:OR0MkOA0vHuBAi/Ta2cokbedpOWXejqS0NaPx4TDW7Y=,tag:hBnp0PIAaoJu3dpmHBQgCg==,type:str]
    BANK_SERVICES_TRANSFER_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:lzhtaW+el1uoQihN/CTGJ/xDWK6AIsjETolj2fW7Y+X51Q==,iv:U8JTiP0ok8Ny1oqrmSIZoxawWZ8456k3C1xxDy/YUYQ=,tag:lrkqwnKESNuKH5UisfwRZA==,type:str]
    BANK_SERVICES_NOTIFICATION_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:4a1OhaX8F24dDMBAJgA5jCjjxSPe93Sra+1+hfrPdF+dzbGojgY=,iv:3dAuOlu7B2UTMju29j3OmQ6DPUkze/O7nTLSCSgf6LQ=,tag:e0OxiKs9GN8zEtIzwGidqQ==,type:str]
    BANK_SERVICES_EXCHANGE_GENERATOR_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:xZC1jpL0e0gwJ+x4fBcgLMctDMEwcN2PDLGk5Bu8avm2JczdAwra6kd89Fk=,iv:KcU+aTyMvIFq1rki8hxV7to5q6fqQZ8Fyo4zyRAAQ/M=,tag:Rgmr5S8vHKi3R9z1SSViiA==,type:str]
postgresqlCredentials:
    password: ENC[AES256_GCM,data:HtgtrD5zrg53rr9bpBDVkAJLTSMEBP8=,iv:4OPXHbtGd/a1pDchIS50d/6S7xvOHkIJr1a7qWWkKzs=,tag:X5JoPBEAX6j1X4OUTLz5tw==,type:str]
keycloakCredentials:
    adminUsername: ENC[AES256_GCM,data:2FLGrEWj7AxRf5mDnkhjMmDnTet8m0w983nT,iv:hTAnkuTFsOuw0ahtySiBI7Fk2J4gaHtUYCKt1cPpKio=,tag:ipykIdKmTJs86shEi5/jqg==,type:str]
    adminPassword: ENC[AES256_GCM,data:tl2zsgrA72PU2PozP9Fg7HDQQs5rI4PGMEH6,iv:lRL92OW2LrnFvOouEI7zTf6guDIQMRu8GFy75f4YFfM=,tag:EY/0FxsiKACt54Wxvm7/Nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yxaztnh2jc4740e33fcxa8gy996a959f2548xucplkss4k483p6ss8jryg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUem1zM3czaXlRRGpvMkdQ
            dm1uOUg4dCtka3JENGpwRU1PSkVGZi9pREVvCnFyNkYzMkpBZlFsb0UrWjBqSjRP
            blJ6NlZKOHBXNWRDcnNLZU5CeXRMS1EKLS0tIFQvNTFQZGF5bTVObVBtdVlJT0Rw
            SmczN1JRUUlzOU1XSEsxZVdaVkpqOEkKdXnvoBznDvisC7fNf5t4lAxeLbUzmWEw
            cBmMmJc6TcbJSPoo7pVKtXms2NK0ou9kXIXgY6o2SW+sanT377urGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-23T18:59:20Z"
    mac: ENC[AES256_GCM,data:s9TnwDuzlIH0ThMMvRR9q7ItLryU1l8o+6hEFEJGvTcEdoInmHdGa/Pa33ssBCOu2zmsRv8x32az4gx7ojYnJ33chr2b9qjVbCMGXoCP1NFhrK2udhhPUSOcZOQUjjFlDf2hJrNyRlchin1pOWDOI5mZgLWTbIdkMmSusP8a460=,iv:nzj0f6tY9vvQS4bj3Y+smE1QiLsfbZsWUVG2pz53nUE=,tag:Nf4DkO9Cs0F9vL1Lq149RQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
