account-service:
  enabled: true

  fullnameOverride: account-service

  image:
    repository: my-bank-account-service

  service:
    port: 8081

  management:
    enabled: true
    port: 8091
    monitoring:
      enabled: true
      alert:
        enabled: false
  probes:
    port: management

  env:
    BANK_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/my-bank
    BANK_DATASOURCE_USERNAME: postgres
    SPRING_JPA_HIBERNATE_DDLAUTO: validate
    SPRING_JPA_OPENINVIEW: "false"
    BANK_BALANCE_RETRY_BACKOFF_MS: "50"
    BANK_BALANCE_RETRY_MAX_ATTEMPTS: "3"
    SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    MANAGEMENT_SERVER_PORT: "8091"
    SERVER_PORT: "8081"

  secretEnv:
    - name: BANK_SERVICES_ACCOUNT_SERVICE_CLIENT_SECRET
      secretName: my-bank-service-credentials
      key: BANK_SERVICES_ACCOUNT_SERVICE_CLIENT_SECRET
    - name: BANK_DATASOURCE_PASSWORD
      secretName: postgresql-credentials
      key: password