api-gateway:
  enabled: false

  fullnameOverride: api-gateway

  image:
    repository: my-bank-api-gateway

  service:
    port: 8080

  management:
    enabled: true
    port: 8090

  probes:
    port: management

  env:
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_FILTERS_0: SetStatus=404
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_ID: block-account-internal-api
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_PREDICATES_0: Path=/api/account/internal/**
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_URI: no://op
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_FILTERS_0: JwtTokenRelay
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_ID: account-service
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_PREDICATES_0: Path=/api/account/**
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_URI: http://account-service:8081
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_FILTERS_0: JwtTokenRelay
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_ID: cash-service
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_PREDICATES_0: Path=/api/cash/**
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_URI: http://cash-service:8082
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_3_FILTERS_0: JwtTokenRelay
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_3_ID: transfer-service
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_3_PREDICATES_0: Path=/api/transfer
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_3_URI: http://transfer-service:8083
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_4_FILTERS_0: JwtTokenRelay
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_4_ID: exchange-service
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_4_PREDICATES_0: Path=/api/exchange/**
    SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_4_URI: http://exchange-service:8086
    MANAGEMENT_SERVER_PORT: "8090"
    SERVER_PORT: "8080"