{{- if .Values.grafanaCredentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  admin-user: {{ .Values.grafanaCredentials.adminUsername | quote }}
  admin-password: {{ .Values.grafanaCredentials.adminPassword | quote }}
  {{- end -}}