{{- if .Values.serviceCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: my-bank-service-credentials
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.serviceCredentials }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}