{{- if .Values.keycloakCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  admin-username: {{ .Values.keycloakCredentials.adminUsername | quote }}
  admin-password: {{ .Values.keycloakCredentials.adminPassword | quote }}
  {{- end }}