spring:
  application:
    name: account-service
  datasource:
    url: ${BANK_DATASOURCE_URL:jdbc:postgresql://localhost:5432/my-bank}
    username: ${BANK_DATASOURCE_USERNAME:postgres}
    password: ${BANK_DATASOURCE_PASSWORD:postgres}
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${BANK_KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/my-bank-realm}
          jwk-set-uri: ${BANK_KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/my-bank-realm/protocol/openid-connect/certs}

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8081