node {
    checkout scm
    load('jenkins/jenkins-service.groovy').runServicePipeline(
        serviceName: 'blocker-service',
        gradleModule: ':blocker-service',
        chartPath: 'helm/charts/spring-service',
        valuesPath: 'helm/values/services/blocker-service.yaml',
        imageRepository: 'my-bank-blocker-service'
    )
}