spring:
  application:
    name: blocker-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${BANK_KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/my-bank-realm}
          jwk-set-uri: ${BANK_KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/my-bank-realm/protocol/openid-connect/certs}

bank:
  services:
    blocker-service:
      blocker:
        max-amount: ${BANK_BLOCKER_SERVICE_MAX_AMOUNT:100000.00}

server:
  port: 8088