spring:
  application:
    name: cash-service
  security:
    oauth2:
      client:
        registration:
          cash-service:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: cash-service
            client-secret: ${CASH_SERVICE_CLIENT_SECRET:}
        provider:
          keycloak:
            token-uri: ${BANK_KEYCLOAK_TOKEN_URI:http://localhost:8180/realms/my-bank-realm/protocol/openid-connect/token}
      resourceserver:
        jwt:
          issuer-uri: ${BANK_KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/my-bank-realm}
          jwk-set-uri: ${BANK_KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/my-bank-realm/protocol/openid-connect/certs}

bank:
  services:
    account-service:
      base-url: ${BANK_ACCOUNT_SERVICE_BASE_URL:http://account-service}
    notification-service:
      base-url: ${BANK_NOTIFICATION_SERVICE_BASE_URL:http://notification-service}
    blocker-service:
      base-url: ${BANK_BLOCKER_SERVICE_BASE_URL:http://blocker-service}

server:
  port: 8082