node {
    checkout scm
    load('jenkins/pipelines/jenkins-service.groovy').runServicePipeline(
        serviceName: 'front-ui-service',
        gradleModule: ':front-ui-service',
        chartPath: 'helm/charts/spring-service',
        valuesPath: 'helm/values/services/front-ui-service.yaml',
        imageRepository: 'my-bank-front-ui-service'
    )
}