node {
    checkout scm
    load('jenkins/pipelines/jenkins-service.groovy').runServicePipeline(
        serviceName: 'account-service',
        gradleModule: ':account-service',
        chartPath: 'helm/charts/spring-service',
        valuesPath: 'helm/values/services/account-service.yaml',
        imageRepository: 'my-bank-account-service'
    )
}