node {
    checkout scm
    load('jenkins/pipelines/jenkins-service.groovy').runServicePipeline(
        serviceName: 'exchange-service',
        gradleModule: ':exchange-service',
        chartPath: 'helm/charts/spring-service',
        valuesPath: 'helm/values/services/exchange-service.yaml',
        imageRepository: 'my-bank-exchange-service'
    )
}